name: Bindings Tests
on:
  push:
    paths:
      - bindings/go/**

jobs:
    ubuntu-latest:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - uses: actions/checkout@v1
      - run: |
          cd bindings/go
          make test
