name: CI
on: [push]

jobs:
    ubuntu-latest:
        runs-on: ubuntu-latest

        steps:
            - name: Clone
              uses: actions/checkout@v1

            - name: Dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install build-essential
                  sudo apt-get install libsdl2-dev;

            - name: Build
              run: |
                make
                make stream

    macOS-latest:
        runs-on: macOS-latest

        steps:
            - name: Clone
              uses: actions/checkout@v1

            - name: Dependencies
              run: |
                  brew update
                  brew install sdl2

            - name: Build
              run: |
                make
                make stream
